export const defaultSite = {
  homeTitle: "Bong's Board Games",
  tagline: 'Play a bot instantly. Sign in when you want a table with someone.',
  footer: 'A small table for turn-based games. More titles will arrive over time.',
  shelves: {
    featured: 'Featured',
    newest: 'New',
    popular: 'Most popular',
    mostPlayers: 'Most players',
    yourMost: 'Your most played',
    lastPlayed: 'Last played',
  },
  games: {
    'tic-tac-toe': {
      title: 'Tic-Tac-Toe',
      blurb: 'Three in a row on a classic 3×3 grid.',
      similarTo: 'Noughts and Crosses',
      published: true,
      featured: true,
      releasedAt: '2026-09-11',
      newUntil: '',
      howToPlay: '',
      rulesDetails: '',
      order: 1,
    },
    'connect-four': {
      title: 'Connect Four',
      blurb: 'Drop discs. Connect four in any direction.',
      similarTo: 'Four in a Row',
      published: true,
      featured: true,
      releasedAt: '2026-09-11',
      newUntil: '',
      howToPlay: '',
      rulesDetails: '',
      order: 2,
    },
    citadels: {
      title: 'Citadels',
      blurb: 'Draft a hidden role each round and build the richest city.',
      similarTo: 'role-draft city builder',
      published: true,
      featured: false,
      releasedAt: '2026-09-12',
      newUntil: '',
      howToPlay: '',
      rulesDetails: '',
      order: 3,
    },
    pioneer: {
      title: 'Pioneer',
      blurb: 'Settle an island rich with wood, clay, sheep, wheat, and stone. Build roads, trade with posts, and vie for the longest route.',
      similarTo: 'island settlement',
      published: true,
      featured: false,
      releasedAt: '2026-09-12',
      newUntil: '',
      howToPlay: '',
      rulesDetails: '',
      order: 4,
    },
  },
};
