export const meta = {
  id: 'citadels',
  title: 'Citadels',
  seats: 4,
  seatsMin: 4,
  seatsMax: 6,
  disconnectMs: 45000,
  previewState: {
    revision: 8,
    seatCount: 4,
    phase: 'main',
    actorSeat: 0,
    turn: 0,
    crownSeat: 0,
    rankCalled: 6,
    faceupDiscard: ['assassin'],
    facedownDiscard: ['hidden'],
    draftRemaining: [],
    players: [
      {
        name: 'You',
        gold: 4,
        hand: ['tavern-1', 'temple-1'],
        city: ['manor-1', 'watchtower-1', 'market-1'],
        roleId: 'merchant',
        roleRevealed: true,
      },
      {
        name: 'Bot',
        gold: 2,
        hand: ['hidden', 'hidden'],
        city: ['church-1', 'prison-1'],
        roleId: null,
        roleRevealed: false,
      },
      {
        name: 'Bot',
        gold: 5,
        hand: ['hidden'],
        city: ['castle-1'],
        roleId: null,
        roleRevealed: false,
      },
      {
        name: 'Bot',
        gold: 1,
        hand: ['hidden', 'hidden', 'hidden'],
        city: ['tavern-2', 'docks-1'],
        roleId: null,
        roleRevealed: false,
      },
    ],
    winner: null,
    draw: false,
    log: [],
  },
};
